
version: '3'
services:
  node1:
    build:
      context: .
    environment:
      - NODE_ID=0
    ports:
      - "5001:5000"

  node2:
    build:
      context: .
    environment:
      - NODE_ID=1
    ports:
      - "5002:5000"

  node3:
    build:
      context: .
    environment:
      - NODE_ID=2
    ports:
      - "5003:5000"
